### ISSUE TITLE
Add boss name Venus medic 

### ISSUE THREAD

**Issue by RedTerminal1912** [gongpha/TFOC-FF2#11]
Hope It no boom tfoc

https://www.dropbox.com/s/niid2q3w1alur2y/Venus%20medic.rar?dl=0

**Comment by gongpha** [comment]
Done yet ?

**Comment by RedTerminal1912** [comment]
I'm not sure about this ask reverse for checking model and materials

**Comment by gongpha** [comment]
@Reversesniper

**Comment by gongpha** [comment]
That looks like this place was abandoned.

**Comment by Reversesniper** [comment]
Bro we already test that boss i guess i gonna add him to pack 4

**Comment by gongpha** [comment]
So, This issue is safe for close now.

**Comment by Reversesniper** [comment]
Maybe
