### ISSUE TITLE
UH

### ISSUE THREAD

**Issue by Draquile** [gongpha/TFOC-FF2#16]
UH

**Monokuma**
![image](https://user-images.githubusercontent.com/54506129/77252356-ea905880-6c85-11ea-9f69-1d867f7aab6f.png)
![image](https://user-images.githubusercontent.com/54506129/77252411-45c24b00-6c86-11ea-9aaa-f0e121c6df5e.png)

Download Link!
https://www.dropbox.com/s/pep6f42jlb2olo0/dgrp.rar?dl=0z

![image](https://user-images.githubusercontent.com/54506129/77252777-c7b37380-6c88-11ea-8627-ac01175347db.png)

UfatSun9z

**Comment by Reversesniper** [comment]
![i here zell](https://user-images.githubusercontent.com/34367924/77252918-b4ed6e80-6c89-11ea-94fe-05cec30708b3.png)

ok ผ่านมั้ง?
