### ISSUE TITLE
JSS and JWS OwO

### ISSUE THREAD

**Issue by RedTerminal1912** [gongpha/TFOC-FF2#17]
Jws
https://www.dropbox.com/s/a0q21glgy1p7jr8/japanese%20winter%20sniper.rar?dl=0

Jss and Jws Duo
https://www.dropbox.com/s/i53p5005esm1iaa/JSS%20and%20JWS%20DUO.rar?dl=0

**Comment by Reversesniper** [comment]
gonna read info

**Comment by RedTerminal1912** [comment]
Fix some file

**Comment by Reversesniper** [comment]
Added to server
