### ISSUE TITLE
UHH part 2

### ISSUE THREAD

**Issue by Draquile** [gongpha/TFOC-FF2#21]
American boot
![image](https://user-images.githubusercontent.com/54506129/77435182-8fd93700-6e14-11ea-9740-cd77bbca7962.png)
Ninjineer
![image](https://user-images.githubusercontent.com/54506129/77435239-a2ec0700-6e14-11ea-98bd-05f737d7c7e2.png)
Bob The Builder
![image](https://user-images.githubusercontent.com/54506129/77436866-910b6380-6e16-11ea-93f2-da5c338348d6.png)
.
.
.
.
.
.
.
.
.
Silanos
[No pic]
but we have

![image](https://user-images.githubusercontent.com/54506129/77437533-5bb34580-6e17-11ea-939d-a83fc2134858.png)

So pls add Silanos :3 or not is up2you

https://www.dropbox.com/s/uc0r5jl9ongau8c/ASSWECAN.rar?dl=0

**Comment by Sun9z** [comment]
bruh why is it not satania?

**Comment by Sun9z** [comment]
wrong label
