### ISSUE TITLE
JSS hentai ready to boom ur server XD jk

### ISSUE THREAD

**Issue by RedTerminal1912** [gongpha/TFOC-FF2#5]
https://www.dropbox.com/s/p1eqd5ovatlwid9/jss%20hentaiv2.rar?dl=0

**Comment by gongpha** [comment]
Is this done ?

**Comment by RedTerminal1912** [comment]
Idk

**Comment by gongpha** [comment]
Done ?

**Comment by gongpha** [comment]
@Sun9z

**Comment by Sun9z** [comment]
No
—
I added milestone because it’s the boss request issue

**Comment by Sun9z** [comment]
Added into TFOC’s Server Files !
(Didn’t put in real-game yet)
