### ISSUE TITLE
add boss in further pack

### ISSUE THREAD

**Issue by Draquile** [gongpha/TFOC-FF2#7]
i don't have server to test it
so if it's bug or problem tell me :)

i think pack 2 have a lot of boss now then add in pack 3 or
 pack 2 if u want

![Virusdoctor](https://user-images.githubusercontent.com/54506129/66821440-9feb1180-ef6c-11e9-8854-d8d7f3a754cd.png)

Virusdoctor

Class : Medic
Live : 2
health formula : (((760+n)*n)^1.04)/2
abilities :
- Super jump(alf-fire)
- Weight-down
- rage
	• Stun player 4 sec,sentry 10 sec
	• Overlay 3 sec
	• Uber 7 sec
	• Outline 10 sec
- lose life
	• pause the game
	• change theme

plugin used :
-dynamicdefaults
-otokiruwc3
-m7abilities
-rageoverlay
-pauseability

Dowload : https://www.dropbox.com/s/yoh2l2d47nzk6rx/Virusdoctor.rar?dl=0

![Magineertic](https://user-images.githubusercontent.com/54506129/66821622-ee001500-ef6c-11e9-8203-dafb8b371a7a.png)

Magineertic

Class : engineer
Live : 1
health formula : (((700+n)*n)^1.04)
abilities :
- Super jump(alf-fire)
- Weight-down
- rage
	• Stun player 4 sec
	• twisted attraction(bring player close to u and explode?)

plugin used :
-dynamicdefaults
-otokiruwc3
-sarysamod plugin number 8 (like Unidentified Producer)

Dowload : https://www.dropbox.com/s/5kpkycj6g2ui5nw/Magineertic.rar?dl=0

ps : if Magineertic have some bug or rage not working just delete it.

**Comment by Sun9z** [comment]
Added Virusdoctor and Magineertic into pack 3.

**Comment by Sun9z** [comment]
close #7

**Comment by Sun9z** [comment]
closed

**Comment by Sun9z** [comment]
close 7

**Comment by Sun9z** [comment]
Closes: #7
