### ISSUE TITLE
Virusdoctor & Magineertic fix version

### ISSUE THREAD

**Issue by Draquile** [gongpha/TFOC-FF2#8]
i forgot to put freak_fortress_2 file in bzip2 and i buff Magineertic(health,twisted attraction dmg&range)

delete da old version and poot da new version

Virusdoctor : https://www.dropbox.com/s/cu155vmihm0ft0g/Virusdoctor.rar?dl=0

Magineertic : https://www.dropbox.com/s/jp171ix3oiruj8l/Magineertic.rar?dl=0

**Comment by Sun9z** [comment]
k den

**Comment by Draquile** [comment]
Virusdoctor
https://www.dropbox.com/s/cu155vmihm0ft0g/Virusdoctor.rar?dl=0

New 1 again ;w;

**Comment by Sun9z** [comment]
k

**Comment by Sun9z** [comment]
Added Magineertic into Pack 1 and Virusdoctor into Pack 2.
