### ISSUE TITLE
I DON'T HAVE PERMISSION TO CLOSE OTHER PEOPLES ISSUE #9

### ISSUE THREAD

**Issue by Sun9z** [gongpha/TFOC-FF2#9]
close issue attempt 1#

**Comment by Sun9z** [comment]
bruh

**Comment by Sun9z** [comment]
(͠≖ ͜ʖ͠≖)

**Comment by Sun9z** [comment]
make sense.

**Comment by gongpha** [comment]
calm down. @Sun9z you aren't a collaborator. Also, the author can close or open an issue that the author made only.

**WHAT'S WRONG WITH YOU ??**
